// Client-side document generators: PBC evidence request list and gap report.
// Both open a print-optimized window (save as PDF via the browser).

function esc(s) {
  return String(s ?? "").replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;")
}

const DOC_STYLE = `
  * { box-sizing: border-box; margin: 0; }
  body { font: 13px/1.5 -apple-system, "Segoe UI", Roboto, sans-serif; color: #1e293b; padding: 32px; max-width: 820px; margin: 0 auto; }
  h1 { font-size: 20px; margin-bottom: 2px; }
  h2 { font-size: 14px; margin: 22px 0 8px; padding-bottom: 4px; border-bottom: 1px solid #e2e8f0; }
  .sub { color: #64748b; font-size: 12px; margin-bottom: 14px; }
  .meta { display: flex; gap: 24px; font-size: 12px; color: #475569; margin-bottom: 6px; }
  .meta b { color: #0f172a; }
  .item { display: flex; gap: 10px; padding: 8px 0; border-bottom: 1px dotted #e2e8f0; page-break-inside: avoid; }
  .box { width: 13px; height: 13px; border: 1.5px solid #94a3b8; border-radius: 3px; flex-shrink: 0; margin-top: 2px; }
  .cid { font-family: ui-monospace, monospace; font-size: 11px; font-weight: 700; color: #334155; flex-shrink: 0; width: 72px; }
  .body { flex: 1; }
  .t { font-weight: 600; font-size: 12.5px; }
  .d { font-size: 12px; color: #475569; margin-top: 1px; }
  .ex { font-size: 11.5px; color: #1e40af; margin-top: 3px; }
  .status { font-size: 10px; font-weight: 700; text-transform: uppercase; letter-spacing: .04em; padding: 1px 7px; border-radius: 999px; flex-shrink: 0; height: fit-content; }
  .s-relevant { background: #dbeafe; color: #1e40af; }
  .s-done { background: #d1fae5; color: #065f46; }
  .s-na { background: #f1f5f9; color: #475569; }
  .s-open { background: #fef3c7; color: #92400e; }
  .footer { margin-top: 26px; padding-top: 10px; border-top: 1px solid #e2e8f0; font-size: 10.5px; color: #94a3b8; }
  @media print { body { padding: 0; } }
`

function openDoc(title, bodyHtml) {
  const win = window.open("", "_blank")
  if (!win) return
  win.document.write(`<!doctype html><html><head><meta charset="utf-8"><title>${esc(title)}</title><style>${DOC_STYLE}</style></head><body>${bodyHtml}<script>window.onload = () => setTimeout(() => window.print(), 250)<\/script></body></html>`)
  win.document.close()
}

// ── PBC / evidence request list ─────────────────────────────────────────
export function exportPBC({ frameworkName, entries, controlLevel = false }) {
  const today = new Date().toISOString().slice(0, 10)
  const rows = entries.map(e => `
    <div class="item">
      <div class="box"></div>
      <div class="cid">${esc(e.code)}</div>
      <div class="body">
        <div class="t">${esc(e.name)}</div>
        <div class="d">${esc(e.what)}</div>
        ${(e.examples || []).map(x => `<div class="ex">&#128247; ${esc(x)}</div>`).join("")}
      </div>
    </div>`).join("")

  openDoc(`Evidence Request List — ${frameworkName}`, `
    <h1>Evidence Request List (PBC)</h1>
    <div class="sub">${esc(frameworkName)} &middot; Generated by FrameDiff &middot; ${today}</div>
    <div class="meta"><span>Prepared for: <b>____________________</b></span><span>Audit period: <b>____________________</b></span><span>Due date: <b>____________</b></span></div>
    <div class="sub">Check each item as evidence is collected. Include the capture date and system name in every screenshot; note the population/scope alongside samples. ${controlLevel ? `${entries.length} controls.` : `${entries.length} control areas.`}</div>
    ${rows}
    <div class="footer">Generated from framediff.vercel.app/evidence. Evidence examples are illustrative and tool-agnostic — the assessor determines sufficiency for your scope. FrameDiff is not affiliated with any framework publisher.</div>
  `)
}

// ── Gap report from triage state ────────────────────────────────────────
export function exportGapReport({ framework, fromVersion, toVersion, changes, triage }) {
  const today = new Date().toISOString().slice(0, 10)
  const groups = { relevant: [], open: [], done: [], na: [] }
  changes.forEach(c => {
    const s = triage[c.id]
    if (s === "relevant") groups.relevant.push(c)
    else if (s === "done") groups.done.push(c)
    else if (s === "na") groups.na.push(c)
    else groups.open.push(c)
  })

  const fmtId = (cid) => !cid ? "" : typeof cid === "string" ? cid : (cid.new || cid.old || "")
  const section = (title, cls, items, note) => items.length === 0 ? "" : `
    <h2>${esc(title)} (${items.length})</h2>
    ${note ? `<div class="sub">${esc(note)}</div>` : ""}
    ${items.map(c => `
      <div class="item">
        <span class="status ${cls}">${esc(title.split(" ")[0])}</span>
        <div class="cid">${esc(fmtId(c.controlId))}</div>
        <div class="body">
          <div class="t">${esc(c.title)}</div>
          ${c.rationale ? `<div class="d">${esc(c.rationale)}</div>` : ""}
        </div>
      </div>`).join("")}`

  const reviewed = groups.relevant.length + groups.done.length + groups.na.length
  openDoc(`Gap Assessment — ${framework.shortName || framework.name}`, `
    <h1>Framework Transition Gap Assessment</h1>
    <div class="sub">${esc(framework.name)} &middot; ${esc(fromVersion)} &rarr; ${esc(toVersion)} &middot; Generated by FrameDiff &middot; ${today}</div>
    <div class="meta">
      <span>Total changes: <b>${changes.length}</b></span>
      <span>Reviewed: <b>${reviewed}</b></span>
      <span>Action required: <b>${groups.relevant.length}</b></span>
      <span>Addressed: <b>${groups.done.length}</b></span>
      <span>Not applicable: <b>${groups.na.length}</b></span>
    </div>
    ${section("Relevant — action required", "s-relevant", groups.relevant, "Changes assessed as applicable to the organization and not yet addressed.")}
    ${section("Open — not yet reviewed", "s-open", groups.open, "Changes not yet triaged; review and classify.")}
    ${section("Done — addressed", "s-done", groups.done)}
    ${section("N/A — not applicable", "s-na", groups.na)}
    <div class="footer">Triage classifications were recorded in the FrameDiff gap-assessment tracker (browser-local). Informational summary — verify each change against official framework documentation before compliance decisions.</div>
  `)
}
